version: "3.4"

services:
  crimsonlmsserver:
    image: crimsonlmsserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      AUTH0_DOMAIN:
      AUTH0_CLIENT_ID:
      AUTH0_CLIENT_SECRET:
      SESSION_SECRET:
      PORT: 3000
      AUTH0_CALLBACK_URL: /login/callback
      PUBLIC_URL: http://localhost:3000
    ports:
      - 3000:3000
